#!/usr/bin/env python3

import argparse
import math
import random


parser = argparse.ArgumentParser(
	description='Generate random sequences in FASTA format')
parser.add_argument('--num', required=False, type=int, default=10,
	metavar='<int>', help='input the number of sequence [%(default)i]')
parser.add_argument('--len', required=False, type=int, default=100,
	metavar='<int>', help='input the length of sequences [%(default)i]')
parser.add_argument('--comp', required=False, type=float, nargs=4,
	default=[0.25,0.25,0.25,0.25], metavar='<float>',
	help='input the probability of each base in the format: A C G T %(default)s')
parser.add_argument('--prefix', required=False, type=str, default='id.',
	help='prefix for identifier [%(default)s]')
parser.add_argument('--seed', required = False, type=int, metavar='<int>',
	help='input the random seed')
arg = parser.parse_args()

if arg.seed:
	random.seed(arg.seed)

assert(math.isclose(sum(arg.comp),1))

for i in range(arg.num):
	print(f'>{arg.prefix}{i+1}')
	seq=''.join(random.choices('ACGT', weights=arg.comp, k=arg.len))
	for i in range(0, len(seq), 80):
		print(seq[i:i+80])

